In [1]:
import pandas as pd

In [2]:
coups_df = pd.read_csv('./data/cline_coups.csv')

In [3]:
coups_df.head(3)

,coup_id,cowcode,country,year,month,day,event_type,unrealized,realized,conspiracy,...,counter,other,noharm,injured,killed,harrest,jailed,tried,fled,exile
0,70003101963,700,Afghanistan,1963,3,10,coup,0,1,0,...,0,0,1,0,0,0,0,0,0,0
1,70007171973,700,Afghanistan,1973,7,17,coup,0,1,0,...,0,0,1,0,0,0,0,0,1,0
2,70009201973,700,Afghanistan,1973,9,20,attempted coup,1,0,0,...,0,0,1,0,0,0,0,0,0,0

In [12]:
coups_df\
    .groupby('country', as_index=False)\
    ['event_type'].value_counts(normalize=True).round(2).sort_values('proportion', ascending=True).head(25)

               country      event_type  proportion
123              Haiti      conspiracy        0.04
36             Burundi      conspiracy        0.07
208           Paraguay      conspiracy        0.07
2          Afghanistan      conspiracy        0.08
211               Peru      conspiracy        0.08
81               Egypt  attempted coup        0.08
149               Laos      conspiracy        0.08
24               Benin      conspiracy        0.10
20          Bangladesh      conspiracy        0.10
153            Lesotho      conspiracy        0.10
163         Madagascar      conspiracy        0.10
159              Libya      conspiracy        0.10
91            Ethiopia      conspiracy        0.10
27             Bolivia      conspiracy        0.11
201           Pakistan      conspiracy        0.11
136               Iraq      conspiracy        0.11
84         El Salvador      conspiracy        0.11
223  Republic of Korea  attempted coup        0.12
186            Myanmar      conspiracy        0.12
185            Myanmar  attempted coup        0.12
278             Turkey      conspiracy        0.12
113          Guatemala      conspiracy        0.12
57               Congo      conspiracy        0.13
262              Syria  attempted coup        0.14
196            Nigeria  attempted coup        0.14